const LifeTrackr = {
  caseName: "Front-end & UI/UX Case",
  projectName: "LifeTrackr",
  platform: "Mobile App",
  platformIcons: ["fa-brands fa-android", "fa-brands fa-apple"],
  techStack: [
    {
      colorFront: { color: "blue" },
      iconFront: "fa-brands fa-react fa-xs",
      nameFront: "React Native",
      colorBack: { color: "blue" },
      iconBack: "bx bx-devices",
      nameBack: "Cross-platform",
    },
    {
      colorFront: { color: "#17CC8B" },
      iconFront: "bx bx-cloud",
      nameFront: "REST API",
      colorBack: { color: "blue" },
      iconBack: "bx bx-lock-alt",
      nameBack: "JWT Auth",
    },
    {
      colorFront: { color: "#04C3FF" },
      iconFront: "bx bxl-redux",
      nameFront: "Redux Saga",
      colorBack: { color: "blue" },
      iconBack: "fa-regular fa-group-arrows-rotate fa-xs",
      nameBack: "AJAX HTTP Requests",
    },
    {
      colorFront: { color: "#3044AA" },
      iconFront: "fa-brands fa-aws fa-xs",
      nameFront: "AWS",
      colorBack: { color: "blue" },
      iconBack: "bx bx-devices",
      nameBack: "Responsive Design",
    },
    {
      colorFront: { color: "#A303DC" },
      iconFront: "fa-brands fa-figma fa-xs",
      nameFront: "Figma",
      colorBack: { color: "blue" },
      iconBack: "fa-regular fa-wand-magic-sparkles fa-xs",
      nameBack: "Neomorphic UI Style",
    },
  ],
};

const Outdoors = {
  caseName: "Front-end & UI/UX Case",
  projectName: "Outdoors",
  platform: "Web App",
  platformIcons: ["bx bxs-devices", "bx bx-desktop"],
  techStack: [
    {
      colorFront: { color: "blue" },
      iconFront: "fa-brands fa-react fa-xs",
      nameFront: "React JS",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "#f06529" },
      iconFront: "fa-brands fa-html5 fa-xs",
      nameFront: "HTML5",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "#CD6799" },
      iconFront: "fa-brands fa-sass fa-xs",
      nameFront: "SASS",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "#A303DC" },
      iconFront: "fa-brands fa-figma fa-xs",
      nameFront: "Figma",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "#17CC8B" },
      iconFront: "bx bx-cloud",
      nameFront: "REST API",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
  ],
};

const EthWallet = {
  caseName: "Full Stack & UI/UX Case",
  projectName: "ETH Wallet",
  platform: "Web APP",
  platformIcons: ["bx bx-desktop", "bx bxs-devices"],
  techStack: [
    {
      colorFront: { color: "blue" },
      iconFront: "fa-brands fa-react fa-xs",
      nameFront: "React JS",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "#f06529" },
      iconFront: "fa-brands fa-html5 fa-xs",
      nameFront: "HTML5",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "#CD6773" },
      iconFront: "bx bxl-sass",
      nameFront: "Styled-Components",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "#FFA000" },
      iconFront: "bx bxl-firebase",
      nameFront: "Firebase",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "purple" },
      iconFront: "fa-brands fa-figma fa-xs",
      nameFront: "Figma",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
  ],
};

const WorkFlow = {
  caseName: "Full Stack & UI/UX Case",
  projectName: "WorkFlow",
  platform: "Mobile APP",
  platformIcons: ["fa-brands fa-android", "fa-brands fa-apple"],
  techStack: [
    {
      colorFront: { color: "blue" },
      iconFront: "fa-brands fa-react fa-xs",
      nameFront: "React Native",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "#04C3FF" },
      iconFront: "bx bxl-redux",
      nameFront: "Redux Thunk",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "#FFA000" },
      iconFront: "bx bxl-firebase",
      nameFront: "Firebase",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "purple" },
      iconFront: "fa-brands fa-figma fa-xs ",
      nameFront: "Figma",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "#0E1126" },
      iconFront: "fa-solid fa-v fa-xs fa-rotate-180",
      nameFront: "Expo",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
  ],
};

const Portfolio = {
  caseName: "Front-End & UI/UX Case",
  projectName: "Portfolio",
  platform: "Web APP",
  platformIcons: ["bx bx-desktop", "bx bxs-devices"],
  techStack: [
    {
      colorFront: { color: "blue" },
      iconFront: "fa-brands fa-react fa-xs",
      nameFront: "React JS",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "#f06529" },
      iconFront: "fa-brands fa-html5 fa-xs",
      nameFront: "HTML5",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "#CD6799" },
      iconFront: "fa-brands fa-sass fa-xs",
      nameFront: "SASS",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "#04C3FF" },
      iconFront: "bx bxl-redux",
      nameFront: "Redux Thunk",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "#17CC8B" },
      iconFront: "bx bx-cloud",
      nameFront: "REST API",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
  ],
};

export const projectsData = [
  LifeTrackr,
  Outdoors,
  EthWallet,
  WorkFlow,
  Portfolio,
];
