const LifeTrackr = {
  caseName: "Front-end & UI/UX Case",
  projectName: "LifeTrackr",
  platform: "Web App",
  techStack: [
    {
      colorFront: { color: "blue" },
      iconFront: "fa-brands fa-react fa-xs",
      nameFront: "React Native",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "white" },
      iconFront: "fa-brands fa-aws fa-xs",
      nameFront: "AWS",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "purple" },
      iconFront: "fa-brands fa-figma fa-xs",
      nameFront: "Figma",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "blue" },
      iconFront: "fa-brands fa-react fa-xs",
      nameFront: "REST API",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "purple" },
      iconFront: "fa-brands fa-figma fa-xs",
      nameFront: "Figma",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
  ],
};

const Outdoors = {
  caseName: "Front-end & UI/UX Case",
  projectName: "Outdoors",
  platform: "Web App",
  techStack: [
    {
      colorFront: { color: "blue" },
      iconFront: "fa-brands fa-react fa-xs",
      nameFront: "React JS",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "orange" },
      iconFront: "fa-brands fa-html5 fa-xs",
      nameFront: "HTML5",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "pink" },
      iconFront: "fa-brands fa-sass fa-xs",
      nameFront: "SASS",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "purple" },
      iconFront: "fa-brands fa-figma fa-xs",
      nameFront: "Figma",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "blue" },
      iconFront: "fa-brands fa-react fa-xs",
      nameFront: "REST API",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
  ],
};

const EthWallet = {
  caseName: "Full Stack & UI/UX Case",
  projectName: "ETH Wallet",
  platform: "Mobile APP",
  techStack: [
    {
      colorFront: { color: "blue" },
      iconFront: "fa-brands fa-react fa-xs",
      nameFront: "React JS",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "orange" },
      iconFront: "fa-brands fa-html5 fa-xs",
      nameFront: "HTML5",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "pink" },
      iconFront: "bx bxl-sass",
      nameFront: "Styled-Components",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "purple" },
      iconFront: "fa-brands fa-figma fa-xs",
      nameFront: "Figma",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "orange" },
      iconFront: "bx bxl-firebase",
      nameFront: "REST API",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
  ],
};

const WorkFlow = {
  caseName: "Full Stack & UI/UX Case",
  projectName: "WorkFlow",
  platform: "Mobile APP",
  techStack: [
    {
      colorFront: { color: "blue" },
      iconFront: "fa-brands fa-react fa-xs",
      nameFront: "React Native",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "blue" },
      iconFront: "bx bxl-redux",
      nameFront: "Redux Thunk",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "orange" },
      iconFront: "bx bxl-firebase",
      nameFront: "REST API",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "purple" },
      iconFront: "fa-brands fa-figma fa-xs",
      nameFront: "Figma",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "orange" },
      iconFront: "bx bxl-firebase",
      nameFront: "REST API",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
  ],
};

const Portfolio = {
  caseName: "Front-End & UI/UX Case",
  projectName: "Portfolio",
  platform: "Web APP",
  techStack: [
    {
      colorFront: { color: "blue" },
      iconFront: "fa-brands fa-react fa-xs",
      nameFront: "React JS",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "orange" },
      iconFront: "fa-brands fa-html5 fa-xs",
      nameFront: "HTML5",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "pink" },
      iconFront: "fa-brands fa-sass fa-xs",
      nameFront: "SASS",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "blue" },
      iconFront: "bx bxl-redux",
      nameFront: "Redux Thunk",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
    {
      colorFront: { color: "orange" },
      iconFront: "bx bxl-firebase",
      nameFront: "REST API",
      colorBack: { color: "blue" },
      iconBack: "bx bxl-redux",
      nameBack: "Redux",
    },
  ],
};

export const projectsData = [
  LifeTrackr,
  Outdoors,
  EthWallet,
  WorkFlow,
  Portfolio,
];
